### ISSUE TITLE
빠른 3G 환경에서 이미지 용량에 의한 로딩속도 차이가 존재

### ISSUE THREAD

**Issue by ahn0min** [fire-tribes/client#48]
https://github.com/fire-tribes/client/assets/89904226/cb52fb8c-0038-4e2c-a4b7-f69117adb704

왼쪽: PNG 오른쪽 SVG
SVG가 PNG보다 용량이 작다고 알고 있었는데 실제로 비교해보면 오히려 PNG가 용량이 더 작습니다.

- png: 113kb
- svg: 584kb

![image](https://github.com/fire-tribes/client/assets/89904226/1d9876c2-6a32-4d0c-b7f0-644d34e2358f)

상황에 따라서 PNG, SVG를 적절히 사용해야 할 것 같습니다.

**Comment by Whale2200d** [comment]
오호... 리팩토링할 때 비교해봐야 할 사안이네요!
